import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";
import { Header } from "./header";

import { Toaster } from "@/components/ui/toaster"
import { Footer } from "./Footer";

const inter = Roboto({ weight: "900", style: "normal", preload: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${inter.className } m-0 p-0 w-screen`}>
        <ConvexClientProvider>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}