import Link from "next/link";
import "./../globals.css";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import { SideNav } from "./side-nav";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="container mx-auto my-32 min-h-[75vh]">
      <div className="flex flex-col md:flex-row gap-8">
        <SideNav />

        <div className="w-full">
          {children}
        </div>
      </div>
    </main>
  );
}